# Generated by Django 4.2.16 on 2025-06-11 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contact_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +123456789 or 012-3456789).', regex='^\\+?[\\d\\s\\-]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g. SW1A 1AA or 12345).', regex='^[A-Za-z0-9\\s\\-]{3,10}$')]),
        ),
    ]
