# Generated by Django 4.2.16 on 2025-01-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orginal_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
